# версия Docker Compose
version: '3.8'

# имена и описания контейнеров, которые должны быть развёрнуты
services:
  # описание контейнера db
  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.7-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - /var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=share
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  share-server:
    container_name: share-server
    build: ./shareIt-server
    ports:
      - "8081:8081"
    # "зависит от",
    depends_on:
      - db
    # переменные окружения
    environment:
      - DB_NAME=share
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
      - SERVER_PORT=8081

  share-gateway:
    container_name: share-gateway
    build: ./shareIt-gateway
    ports:
      - "8080:8080"
    # "зависит от",
    depends_on:
      - share-server
    environment:
          - HOST=share-server


