drop table if exists users, items;

create table if not exists users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(120) not null,
    name varchar(100)
);

create table if not exists items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) not null,
    description varchar(500) not null,
    owner bigint,
    available boolean
);